version: '3.8'

services:
  backend:
    build: 
      context: ./BACKEND/EventTicketingSystem
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker'
    restart: always

  frontend:
    build: 
      context: ./FRONTEND/ticketing-system
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
    