apiVersion: v1
kind: Secret
metadata:
  name: eventx-backend-secret
type: Opaque
data:
  DATASOURCE_URL: jdbc:mysql://root:XMAEWHYuaVBQAWYuJKxgjHuVUyicPPLc@tramway.proxy.rlwy.net:53777/railway
  DATASOURCE_USERNAME: root
  DATASOURCE_PASSWORD: XMAEWHYuaVBQAWYuJKxgjHuVUyicPPLc
  GOOGLE_CLIENT_ID: 311145104258-hh2g1db9ff4kcptutnhf57ndp99gmhnl.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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
  JWT_SECRET: SecretKeyToGenJWTsMustBeLongerThan256BitsForHS512AlgorithmOrStandardForHS256
  JWT_EXPIRATION_MS: 86400000
  QR_SECRET_SALT: SuperSecretKeyForQRHashing123!
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: 587
  MAIL_USERNAME: thisalth@gmail.com
  MAIL_PASSWORD: djty sash htho xmts