apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventx-backend-deployment
  labels:
    app: eventx-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventx-backend
  template:
    metadata:
      labels:
        app: eventx-backend
    spec:
      containers:
      - name: eventx-backend
        image: acr.azurecr.io/eventx-backend:v1
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: event-mysql-server.mysql.database.azure.com
        - name: DB_NAME
          value: eventxdb
        - name: DB_USER
          value: eventxadmin
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        