apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventx-backend-deployment
  labels:
    app: eventx-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventx-backend
  template:
    metadata:
      labels:
        app: eventx-backend
    spec:
      containers:
      - name: eventx-backend
        image: acreventthisal.azurecr.io/eventx-backend:v1
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: DATABASE_URL
          value: jdbc:mysql://event-mysql-server.mysql.database.azure.com:3306/eventxdb?useSSL=true&requireSSL=true
        - name: DATABASE_USERNAME
          value: eventxadmin
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eventx-backend-secret
              key: DB_PASSWORD
        - name: CORS_ALLOWED_ORIGINS
          value: http://20.44.206.26
        - name: FRONTEND_URL
          value: http://20.44.206.26
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: eventx-backend-secret
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: eventx-backend-secret
              key: GOOGLE_CLIENT_SECRET
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: eventx-backend-secret
              key: JWT_SECRET
        - name: JWT_EXPIRATION_MS
          valueFrom:
            secretKeyRef:
              name: eventx-backend-secret
              key: JWT_EXPIRATION_MS
        - name: QR_SECRET_SALT
          valueFrom:
            secretKeyRef:
              name: eventx-backend-secret
              key: QR_SECRET_SALT
        - name: MAIL_HOST
          valueFrom:
            secretKeyRef:
              name: eventx-backend-secret
              key: MAIL_HOST
        - name: MAIL_PORT
          valueFrom:
            secretKeyRef:
              name: eventx-backend-secret
              key: MAIL_PORT
        - name: MAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: eventx-backend-secret
              key: MAIL_USERNAME
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eventx-backend-secret
              key: MAIL_PASSWORD
              
        