apiVersion: v1
kind: Service
metadata:
  name: eventx-frontend-service
  labels:
    app: eventx-frontend
spec:
  type: LoadBalancer
  selector:
    app: eventx-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80